FROM node:lts-alpine
WORKDIR /client
#ENV PATH /app/node_modules/.bin:$PATH
# install project dependencies
#RUN npm install -g @vue/cli


# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . /client
COPY package*.json ./
RUN npm install

# vue ui --headless --port 8000 --host 0.0.0.0
#CMD [ "vue", "ui", "--headless" , "--port", "8000",  "--host", "0.0.0.0" ]

CMD [ "npm", "run", "serve", "--", "--port", "80" ]